name: "test-utils-service"
cluster_env: test-utils-env
ray_serve_config:
  import_path: test_utils_serve.test:build_app
  runtime_env:
    working_dir: "https://github.com/GeneDer/test_anyscale_deployments/archive/refs/heads/main.zip"
