grpc_options:

  port: 9002

  grpc_servicer_functions:

    - user_defined_protos_pb2_grpc.add_UserDefinedServiceServicer_to_server

#    - user_defined_protos_pb2_grpc.add_FruitServiceServicer_to_server

applications:

  - name: app1

#    route_prefix: /

    import_path: test_deployment_v2:g

    runtime_env: {}
