# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_defined_protos.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19user_defined_protos.proto\x12\x11userdefinedprotos\"<\n\x12UserDefinedMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x66oo\x18\x02 \x01(\t\x12\x0b\n\x03num\x18\x03 \x01(\x03\"7\n\x13UserDefinedResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t\x12\x0e\n\x06num_x2\x18\x02 \x01(\x03\"\x15\n\x13UserDefinedMessage2\"(\n\x14UserDefinedResponse2\x12\x10\n\x08greeting\x18\x01 \x01(\t\"=\n\x0c\x46ruitAmounts\x12\x0e\n\x06orange\x18\x01 \x01(\x03\x12\r\n\x05\x61pple\x18\x02 \x01(\x03\x12\x0e\n\x06\x62\x61nana\x18\x03 \x01(\x03\"\x1b\n\nFruitCosts\x12\r\n\x05\x63osts\x18\x01 \x01(\x02\"\x0f\n\rRoutesRequest\"*\n\x0eRoutesResponse\x12\x18\n\x10\x61pplication_name\x18\x01 \x03(\t\"\x10\n\x0eHealthzRequest\"#\n\x0fHealthzResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x83\x03\n\x12UserDefinedService\x12Y\n\x08__call__\x12%.userdefinedprotos.UserDefinedMessage\x1a&.userdefinedprotos.UserDefinedResponse\x12X\n\x07Method1\x12%.userdefinedprotos.UserDefinedMessage\x1a&.userdefinedprotos.UserDefinedResponse\x12Z\n\x07Method2\x12&.userdefinedprotos.UserDefinedMessage2\x1a\'.userdefinedprotos.UserDefinedResponse2\x12\\\n\tStreaming\x12%.userdefinedprotos.UserDefinedMessage\x1a&.userdefinedprotos.UserDefinedResponse0\x01\x32\\\n\x0c\x46ruitService\x12L\n\nFruitStand\x12\x1f.userdefinedprotos.FruitAmounts\x1a\x1d.userdefinedprotos.FruitCosts2\xbc\x01\n\x0fServeAPIService\x12R\n\x0bServeRoutes\x12 .userdefinedprotos.RoutesRequest\x1a!.userdefinedprotos.RoutesResponse\x12U\n\x0cServeHealthz\x12!.userdefinedprotos.HealthzRequest\x1a\".userdefinedprotos.HealthzResponseB:\n#io.ray.examples.user_defined_protosB\x11UserDefinedProtosP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_defined_protos_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#io.ray.examples.user_defined_protosB\021UserDefinedProtosP\001'
  _USERDEFINEDMESSAGE._serialized_start=48
  _USERDEFINEDMESSAGE._serialized_end=108
  _USERDEFINEDRESPONSE._serialized_start=110
  _USERDEFINEDRESPONSE._serialized_end=165
  _USERDEFINEDMESSAGE2._serialized_start=167
  _USERDEFINEDMESSAGE2._serialized_end=188
  _USERDEFINEDRESPONSE2._serialized_start=190
  _USERDEFINEDRESPONSE2._serialized_end=230
  _FRUITAMOUNTS._serialized_start=232
  _FRUITAMOUNTS._serialized_end=293
  _FRUITCOSTS._serialized_start=295
  _FRUITCOSTS._serialized_end=322
  _ROUTESREQUEST._serialized_start=324
  _ROUTESREQUEST._serialized_end=339
  _ROUTESRESPONSE._serialized_start=341
  _ROUTESRESPONSE._serialized_end=383
  _HEALTHZREQUEST._serialized_start=385
  _HEALTHZREQUEST._serialized_end=401
  _HEALTHZRESPONSE._serialized_start=403
  _HEALTHZRESPONSE._serialized_end=438
  _USERDEFINEDSERVICE._serialized_start=441
  _USERDEFINEDSERVICE._serialized_end=828
  _FRUITSERVICE._serialized_start=830
  _FRUITSERVICE._serialized_end=922
  _SERVEAPISERVICE._serialized_start=925
  _SERVEAPISERVICE._serialized_end=1113
# @@protoc_insertion_point(module_scope)
