proxy_location: EveryNode

http_options:

  host: 0.0.0.0

  port: 8000

  request_timeout_s: 2

applications:

- name: app1

  route_prefix: /

  import_path: timeout:app
#  import_path: streaming:app

  runtime_env: {}

  deployments:

  - name: sleep
#  - name: Textbot
