
proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

applications:
- name: serve_model
  route_prefix: /serve
  import_path: serve_model:serve_model_app
  runtime_env: {}
  deployments:
  - name: ModelServer
    num_replicas: 1
    health_check_timeout_s: 30
    ray_actor_options:
      num_cpus: 0.2

