# helm upgrade -i loki grafana/loki-distributed -n loki -f distributed_loki_values.yaml
loki:
  structuredConfig:
    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
    storage_config:
      aws:
        s3: s3://us-west-2/gene-dev2
      boltdb_shipper:
        shared_store: aws
    schema_config:
      configs:
        - from: 2024-01-08
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
