# anyscale services rollout -f service.yaml
name: "obs-logs"
#cluster_env: log-fix:1
ray_serve_config:
  applications:
    - name: app
      route_prefix: /
      import_path: deployment_demo:app
      runtime_env:
        env_vars:
          RAY_SERVE_LOG_TO_STDERR: '0'
    - name: app2
      route_prefix: /app2
      import_path: deployment_demo:app2
      runtime_env:
        env_vars:
          RAY_SERVE_LOG_TO_STDERR: '0'
